### ISSUE TITLE
prevent a LmacRxBlk:1 overbuffer

### ISSUE THREAD

**Issue by ghost** [circuitsforfun/ESP_Hue#2]
after the delay at the end of each function you schould emty the receive buffer to prevent a LmacRxBlk:1 overbuffer. i.e. 

delay(10);
String line; // waste it
  while(_client->available()){
    line = _client->readString();
}

peter

**Comment by rwardlow** [comment]
The receive buffer needs to be returned at the end of the function call to where it was called.
If the buffer is emptied then it would return an empty string so I'm not sure I follow your logic, also I've not run into any LmacRxBlk:1 errors so far, can you give some examples of when you are running into it?
Are you trying to make multiple connections to the ESP at the same time?
