### ISSUE TITLE
is it compatible with esp32?

### ISSUE THREAD

**Issue by drunkscientist** [circuitsforfun/ESP_Hue#7]
basically title: is this specific to esp8266 or will it work with an esp32?

**Comment by circuitsforfun** [comment]
I believe it should be, I haven't tried it since I haven't used my Hue lights in a really long time.
It's possible some changes to WiFiClient on ESP32 could have broken something but I don't think so.

**Comment by SamsTheNerd** [comment]
I had to change `#include <ESP8266WiFi.h>` in ESPHue.h to just `#include <WiFi.h>` but otherwise it seems to work fine!

**Comment by drunkscientist** [comment]
> I had to change `#include <ESP8266WiFi.h>` in ESPHue.h to just `#include <WiFi.h>` but otherwise it seems to work fine!

good enough for me
